package elearning.sfg.beer.order.service.domain;

public enum BeerOrderEventEnum {
    VALIDATION_REQUESTED, VALIDATION_APPROVED, VALIDATION_FAILED,
    ALLOCATION_REQUESTED, ALLOCATION_APPROVED, ALLOCATION_NO_INVENTORY_FOUND, ALLOCATION_FAILED, PICKED_UP,
    DELIVERY_FAILED, ORDER_CANCELLED
}