# Use root/example as user/password credentials, run  docker-compose -f .\docker-compose.yml up
version: '3.1'
services:
  db:
    image: mysql:latest
    volumes:
      - "C:/docker-spring/db:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306